function data()
return {
  en = {
    FXN5C_ROOF_ANIMATION_NAME = "Cooling equipment animation display",
    FXN5C_ROOF_ANIMATION_TOOLTIP = "Fans rotate and roof shutters wave. Large shutters stay open in every mode. Display only, not thermal control; reload after changing options.",
    FXN5C_ROOF_ANIMATION_ALL = "Fans + louvers",
    FXN5C_ROOF_ANIMATION_FANS = "Fans only",
    FXN5C_ROOF_ANIMATION_STATIC = "Static",
    MOD_NAME = "FXN5C v0.37 — China Railway & Jinwen Railway / 10 Variants",
    MOD_DESC = "[h1]China Railway FXN5C Diesel Locomotive[/h1]\nChina Railway blue and Jinwen Railway liveries, ten numbered variants for Transport Fever 2.\n\n[h2]Contents[/h2]\nChina Railway: 0051, 0066 (Shanghai); 0096, 0102 (Nanjing East); 0057, 0081 (Hangzhou); 0035, 0115 (Xuzhou).\nJinwen Railway: 7005, 7006. Two purchase groups, I/II end markings, multiple LODs and directional lighting.\n\n[h2]In-game configuration[/h2]\nPower: 3530 kW. Tractive effort: 580 kN. Top speed: 120 km/h. Weight: 150 t.\nAvailable in all years by default; optionally keep model years (CR: 2024, Jinwen: 2025). Depot markings and dates are project configurations, not certified real-world histories.\n\n[h2]Version and limitations[/h2]\nv0.37 refines roof sections/equipment, both-side radiator layouts and paint continuity, and closes unintended see-through gaps with internal duct surfaces. Fans rotate. Large louvers stay open at 55 degrees in all display modes. Small roof louvers use a top-to-bottom 0.8-second wave, 40-degree maximum opening and 9 larger blades per window at near LOD. These are display settings, not thermal simulation. This is a reference-based reconstruction, not factory CAD. Linkage rods still use deforming skinning rather than exact rigid joints. Extreme curves and hidden structures need further refinement. Native resources, animation transforms and clearance have passed offline checks; systematic in-game validation is still pending. Project renders are not game screenshots. Per-number leading inner-lamp colors are custom configurations, not claims about real wiring.\n\n[h2]Editable models and community refinement[/h2]\n[url=https://github.com/Manfredss/fxn5c-tpf2]Source files, issues and contribution guide[/url]\nEditable Blender scenes and generation/checking scripts are provided. The v0.37 SourceKit includes the required v0.36 baseline. No new FBX export is included; historical FBXs represent v0.24 only. The incremental build has historical baseline dependencies; read the build guide first.\n\n[h2]License[/h2]\nOriginal models, textures and asset data: CC BY-NC-SA 4.0 (attribution, noncommercial, share alike). You may modify and share noncommercial adaptations under that license without asking each time. Credit the project, link the license and describe your changes.\nOriginal program logic: MIT (commercial code use permitted, not commercial model use). Third-party railway marks, font designs and reference materials are excluded from these grants. See the repository license scope and notices.\n\n[h2]Credits and feedback[/h2]\nProject initiator/reviewer: Manfredss / [ihtw] DisguiseMyse1f. AI-assisted procedural modeling and scripting were used. Thanks to reference contributors; Dreamrail illustrations informed structural reconstruction. Original reference images are not distributed. This is not an official manufacturer, railway-operator or Dreamrail release.\nBack up saves and avoid enabling duplicate local/Workshop copies. Please report version, number, reproduction steps and screenshots. Improvements to bogies, linkages, paint and testing are welcome!\n\n[url=https://github.com/Manfredss/fxn5c-tpf2/releases/tag/v0.37]v0.37 release notes, previews and SourceKit[/url]\n",
    FXN5C_YEAR_POLICY_NAME = "Vehicle availability years",
    FXN5C_YEAR_POLICY_TOOLTIP = "Only these FXN5C variants and their two purchase-group headers are affected. Ignore years: available in every game year. Keep model years: CR from 2024, Jinwen from 2025. Existing purchased vehicles are not deleted.",
    FXN5C_YEAR_IGNORE = "Ignore years (default)",
    FXN5C_YEAR_KEEP = "Keep model years (2024 / 2025)",
    VEHICLE_FXN5C_MENU_CR_NAME = "FXN5C — China Railway Blue",
    VEHICLE_FXN5C_MENU_CR_DESC = "China Railway blue: eight numbered variants. Select a vehicle within this group. Depot assignments are customized at the user’s request.",
    VEHICLE_FXN5C_MENU_JINWEN_NAME = "FXN5C — Jinwen Railway",
    VEHICLE_FXN5C_MENU_JINWEN_DESC = "Jinwen Railway blue/white/red: 7006 and 7005. Select a vehicle within this group. Depot assignments are customized at the user’s request.",
    VEHICLE_FXN5C_0051_NAME = "FXN5C 0051 — China Railway Blue / Shanghai Bureau · Shanghai Depot",
    VEHICLE_FXN5C_0051_DESC = "FXN5C 0051, China Railway Blue; Shanghai Bureau · Shanghai Depot markings. Co-Co diesel locomotive, 3,530 kW, 120 km/h. This depot assignment is a user-requested customization, not an officially verified allocation. Dimensions and hidden details are photo-based approximations. The connecting rod uses deforming skinning, not rigid mechanical IK.",
    VEHICLE_FXN5C_0096_NAME = "FXN5C 0096 — China Railway Blue / Shanghai Bureau · Nanjing East Depot",
    VEHICLE_FXN5C_0096_DESC = "FXN5C 0096, China Railway Blue; Shanghai Bureau · Nanjing East Depot markings. Co-Co diesel locomotive, 3,530 kW, 120 km/h. This depot assignment is a user-requested customization, not an officially verified allocation. Dimensions and hidden details are photo-based approximations. The connecting rod uses deforming skinning, not rigid mechanical IK.",
    VEHICLE_FXN5C_0102_NAME = "FXN5C 0102 — China Railway Blue / Shanghai Bureau · Nanjing East Depot",
    VEHICLE_FXN5C_0102_DESC = "FXN5C 0102, China Railway Blue; Shanghai Bureau · Nanjing East Depot markings. Co-Co diesel locomotive, 3,530 kW, 120 km/h. This depot assignment is a user-requested customization, not an officially verified allocation. Dimensions and hidden details are photo-based approximations. The connecting rod uses deforming skinning, not rigid mechanical IK.",
    VEHICLE_FXN5C_0057_NAME = "FXN5C 0057 — China Railway Blue / Shanghai Bureau · Hangzhou Depot",
    VEHICLE_FXN5C_0057_DESC = "FXN5C 0057, China Railway Blue; Shanghai Bureau · Hangzhou Depot markings. Co-Co diesel locomotive, 3,530 kW, 120 km/h. This depot assignment is a user-requested customization, not an officially verified allocation. Dimensions and hidden details are photo-based approximations. The connecting rod uses deforming skinning, not rigid mechanical IK.",
    VEHICLE_FXN5C_0081_NAME = "FXN5C 0081 — China Railway Blue / Shanghai Bureau · Hangzhou Depot",
    VEHICLE_FXN5C_0081_DESC = "FXN5C 0081, China Railway Blue; Shanghai Bureau · Hangzhou Depot markings. Co-Co diesel locomotive, 3,530 kW, 120 km/h. This depot assignment is a user-requested customization, not an officially verified allocation. Dimensions and hidden details are photo-based approximations. The connecting rod uses deforming skinning, not rigid mechanical IK.",
    VEHICLE_FXN5C_0066_NAME = "FXN5C 0066 — China Railway Blue / Shanghai Bureau · Shanghai Depot",
    VEHICLE_FXN5C_0066_DESC = "FXN5C 0066, China Railway Blue; Shanghai Bureau · Shanghai Depot markings. Co-Co diesel locomotive, 3,530 kW, 120 km/h. This depot assignment is a user-requested customization, not an officially verified allocation. Dimensions and hidden details are photo-based approximations. The connecting rod uses deforming skinning, not rigid mechanical IK.",
    VEHICLE_FXN5C_0035_NAME = "FXN5C 0035 — China Railway Blue / Shanghai Bureau · Xuzhou Depot",
    VEHICLE_FXN5C_0035_DESC = "FXN5C 0035, China Railway Blue; Shanghai Bureau · Xuzhou Depot markings. Co-Co diesel locomotive, 3,530 kW, 120 km/h. This depot assignment is a user-requested customization, not an officially verified allocation. Dimensions and hidden details are photo-based approximations. The connecting rod uses deforming skinning, not rigid mechanical IK.",
    VEHICLE_FXN5C_0115_NAME = "FXN5C 0115 — China Railway Blue / Shanghai Bureau · Xuzhou Depot",
    VEHICLE_FXN5C_0115_DESC = "FXN5C 0115, China Railway Blue; Shanghai Bureau · Xuzhou Depot markings. Co-Co diesel locomotive, 3,530 kW, 120 km/h. This depot assignment is a user-requested customization, not an officially verified allocation. Dimensions and hidden details are photo-based approximations. The connecting rod uses deforming skinning, not rigid mechanical IK.",
    VEHICLE_FXN5C_7006_NAME = "FXN5C 7006 — Jinwen Railway / Jinwen Railway · Wenzhou Depot",
    VEHICLE_FXN5C_7006_DESC = "FXN5C 7006, Jinwen Railway; Jinwen Railway · Wenzhou Depot markings. Co-Co diesel locomotive, 3,530 kW, 120 km/h. This depot assignment is a user-requested customization, not an officially verified allocation. Dimensions and hidden details are photo-based approximations. The connecting rod uses deforming skinning, not rigid mechanical IK.",
    VEHICLE_FXN5C_7005_NAME = "FXN5C 7005 — Jinwen Railway / Jinwen Railway · Wenzhou Depot",
    VEHICLE_FXN5C_7005_DESC = "FXN5C 7005, Jinwen Railway; Jinwen Railway · Wenzhou Depot markings. Co-Co diesel locomotive, 3,530 kW, 120 km/h. This depot assignment is a user-requested customization, not an officially verified allocation. Dimensions and hidden details are photo-based approximations. The connecting rod uses deforming skinning, not rigid mechanical IK.",
    VEHICLE_FXN5C_NAME = "FXN5C 0051 — China Railway Blue / Shanghai Bureau · Shanghai Depot",
    VEHICLE_FXN5C_DESC = "FXN5C 0051, China Railway Blue; Shanghai Bureau · Shanghai Depot markings. Co-Co diesel locomotive, 3,530 kW, 120 km/h. This depot assignment is a user-requested customization, not an officially verified allocation. Dimensions and hidden details are photo-based approximations. The connecting rod uses deforming skinning, not rigid mechanical IK.",
    VEHICLE_FXN5C_JINWEN_NAME = "FXN5C 7006 — Jinwen Railway / Jinwen Railway · Wenzhou Depot",
    VEHICLE_FXN5C_JINWEN_DESC = "FXN5C 7006, Jinwen Railway; Jinwen Railway · Wenzhou Depot markings. Co-Co diesel locomotive, 3,530 kW, 120 km/h. This depot assignment is a user-requested customization, not an officially verified allocation. Dimensions and hidden details are photo-based approximations. The connecting rod uses deforming skinning, not rigid mechanical IK.",
  },
  zh_CN = {
    FXN5C_ROOF_ANIMATION_NAME = "散热设备动态展示",
    FXN5C_ROOF_ANIMATION_TOOLTIP = "风扇持续旋转；车顶小百叶波浪开合。大散热窗始终打开，所有动画选项均保留此姿态。展示动画，非温控模拟；改选项后重载存档。",
    FXN5C_ROOF_ANIMATION_ALL = "风扇＋百叶（展示）",
    FXN5C_ROOF_ANIMATION_FANS = "仅风扇",
    FXN5C_ROOF_ANIMATION_STATIC = "静态",
    MOD_NAME = "中国铁路复兴内5C（FXN5C）",
    MOD_DESC = "[h1]中国铁路复兴内5C（FXN5C）内燃机车[/h1]\n[h1]强 于 瓜 爷[/h1]\n戚墅堰机车厂作品\n\n老将的故事留在铁道边，新人的答卷交给长大坡道。\n这一次，让 FXN5C 接过你路网里的重载交路。挂好车钩，开放信号——下一趟，复兴出发。\n从一台能开进游戏的机车，到一台经得起细看的模型，还有不少路要走。本项目开放可编辑源文件，欢迎喜欢 FXN5C 的朋友继续精细化：一个轴箱、一段管路、一处涂装边界、更真实的风笛/电笛，都是有价值的改进。\n\n[h2]v0.37 更新[/h2]\n车顶轮廓与设备重新细化，修正两侧散热窗布局和国铁/金温涂装衔接，补充风扇与排气口腔体内壁。风扇可旋转；大散热窗百叶固定打开 55°；小百叶逐片波浪开合，0.8 秒一轮、最大 40°，近景每窗 9 片，叶片较前版加大。\n保留全部动画、仅风扇、静态三种展示选项；大散热窗在三种模式下均常开。更改选项后请重载。\n[url=https://github.com/Manfredss/fxn5c-tpf2/releases/tag/v0.37]完整更新说明、动画预览与源文件下载[/url]\n原生资源与动画离线检查已通过；本版尚未完成系统游戏/Model Editor 实测。配图为离线预览，不是游戏截图；动画参数不代表实车温控模拟。\n\n[h2]MOD 内容[/h2]\n[list]\n[*]国铁蓝：上局沪段 0051、0066；上局宁东段 0096、0102；上局杭段 0057、0081；上局徐段 0035、0115。\n[*]金温铁路：7005、7006。\n[/list]\n[h2]游戏参数[/h2]\n[list]\n[*]功率：3530 kW\n[*]牵引力：580 kN\n[*]最高速度：120 km/h\n[*]重量：150 t\n[*]出现年份：默认不限年份；可在模组参数中选择国铁 2024 年起、金温 2025 年起。\n[/list]\n以上为模组配置；配属与年份不作为实车履历证明。\n\n[h2]已知不足[/h2]\n车顶已经多轮细化，仍不是厂家 CAD；转向架细节没有很好的还原出来；车钩未与现有国铁 mod（例如布佬的 mod）对齐；司机室内部只是草草建模等。\n模型根据多角度照片、视频以及绘画参考重建。连接杆仍为蒙皮近似，可能弯曲／伸缩，极端曲线和隐藏结构仍待完善。前端内侧红／白灯按车号固定分配，不表示实车配置。\n\n[h2]安装与反馈[/h2]\n请先备份存档，不要同时启用同一模组的本地版和工坊版。遇到问题请提供版本、车号、复现步骤和截图，可在留言区或 GitHub Issues 反馈。\n\n[h2]模型源文件与授权[/h2]\n[url=https://github.com/Manfredss/fxn5c-tpf2]GitHub：Manfredss/fxn5c-tpf2[/url]\n提供可编辑 Blender 场景、生成／检查脚本与贡献指南。v0.37 SourceKit 附件包含必要的 v0.36 构建基线；本版未新导出静态 FBX，仓库旧 FBX 仅代表 v0.24。历史增量构建有基线依赖，请先阅读构建说明。\n[b]原创模型与贴图：CC BY-NC-SA 4.0（署名—非商业性使用—相同方式共享）。[/b]\n允许在许可范围内修改、重涂及公开分享非商用改进版，无需逐次申请；请保留署名、许可链接并说明修改，注意：不得未经另行授权用于商业目的！\n原创脚本逻辑采用 MIT，允许脚本商用，但不授予模型商用权。第三方铁路标志、字形及资料不包含在本项目的授权范围内，完整边界见仓库许可与第三方说明。\n\n[h2]制作与致谢[/h2]\n制作使用 GPT6-Astra、Blender 以及 python 建模与脚本开发（100刀一个月的 Pro 站起来狠狠蹬）\n感谢提供实车照片与资料的朋友；结构参考包括 Dreamrail 绘画。参考原图不随模组分发；参考作者不等同于本项目合作作者或授权方。\n本项目非厂家、铁路运营方或 Dreamrail 官方作品。欢迎一起把它做得更好。\n",
    FXN5C_YEAR_POLICY_NAME = "车辆可用年份",
    FXN5C_YEAR_POLICY_TOOLTIP = "仅影响本模组10个车号及2个购买分组。忽略年份：任意游戏年份可购；保留模型年份：国铁2024年起、金温2025年起。不会删除已经购买的车辆。",
    FXN5C_YEAR_IGNORE = "忽略年份（默认）",
    FXN5C_YEAR_KEEP = "保留模型年份（2024／2025）",
    VEHICLE_FXN5C_MENU_CR_NAME = "复兴5C · 国铁蓝",
    VEHICLE_FXN5C_MENU_CR_DESC = "国铁蓝涂装，共8个车号。请在分组中选择具体车辆；配属标识按用户要求定制。",
    VEHICLE_FXN5C_MENU_JINWEN_NAME = "复兴5C · 金温铁路",
    VEHICLE_FXN5C_MENU_JINWEN_DESC = "金温铁路蓝白红涂装，包含7006、7005。请在分组中选择具体车辆；配属标识按用户要求定制。",
    VEHICLE_FXN5C_0051_NAME = "复兴5C · 国铁蓝 FXN5C 0051 · 上局沪段",
    VEHICLE_FXN5C_0051_DESC = "FXN5C 0051，国铁蓝涂装；车身配属标识“上局沪段”。Co-Co轴式内燃机车，3530千瓦，120公里/小时。配属按用户要求定制，非官方核验结论。部分尺寸和隐藏细节为照片估算；连接杆为会变形的蒙皮跟随，非刚性机械IK。",
    VEHICLE_FXN5C_0096_NAME = "复兴5C · 国铁蓝 FXN5C 0096 · 上局宁东段",
    VEHICLE_FXN5C_0096_DESC = "FXN5C 0096，国铁蓝涂装；车身配属标识“上局宁东段”。Co-Co轴式内燃机车，3530千瓦，120公里/小时。配属按用户要求定制，非官方核验结论。部分尺寸和隐藏细节为照片估算；连接杆为会变形的蒙皮跟随，非刚性机械IK。",
    VEHICLE_FXN5C_0102_NAME = "复兴5C · 国铁蓝 FXN5C 0102 · 上局宁东段",
    VEHICLE_FXN5C_0102_DESC = "FXN5C 0102，国铁蓝涂装；车身配属标识“上局宁东段”。Co-Co轴式内燃机车，3530千瓦，120公里/小时。配属按用户要求定制，非官方核验结论。部分尺寸和隐藏细节为照片估算；连接杆为会变形的蒙皮跟随，非刚性机械IK。",
    VEHICLE_FXN5C_0057_NAME = "复兴5C · 国铁蓝 FXN5C 0057 · 上局杭段",
    VEHICLE_FXN5C_0057_DESC = "FXN5C 0057，国铁蓝涂装；车身配属标识“上局杭段”。Co-Co轴式内燃机车，3530千瓦，120公里/小时。配属按用户要求定制，非官方核验结论。部分尺寸和隐藏细节为照片估算；连接杆为会变形的蒙皮跟随，非刚性机械IK。",
    VEHICLE_FXN5C_0081_NAME = "复兴5C · 国铁蓝 FXN5C 0081 · 上局杭段",
    VEHICLE_FXN5C_0081_DESC = "FXN5C 0081，国铁蓝涂装；车身配属标识“上局杭段”。Co-Co轴式内燃机车，3530千瓦，120公里/小时。配属按用户要求定制，非官方核验结论。部分尺寸和隐藏细节为照片估算；连接杆为会变形的蒙皮跟随，非刚性机械IK。",
    VEHICLE_FXN5C_0066_NAME = "复兴5C · 国铁蓝 FXN5C 0066 · 上局沪段",
    VEHICLE_FXN5C_0066_DESC = "FXN5C 0066，国铁蓝涂装；车身配属标识“上局沪段”。Co-Co轴式内燃机车，3530千瓦，120公里/小时。配属按用户要求定制，非官方核验结论。部分尺寸和隐藏细节为照片估算；连接杆为会变形的蒙皮跟随，非刚性机械IK。",
    VEHICLE_FXN5C_0035_NAME = "复兴5C · 国铁蓝 FXN5C 0035 · 上局徐段",
    VEHICLE_FXN5C_0035_DESC = "FXN5C 0035，国铁蓝涂装；车身配属标识“上局徐段”。Co-Co轴式内燃机车，3530千瓦，120公里/小时。配属按用户要求定制，非官方核验结论。部分尺寸和隐藏细节为照片估算；连接杆为会变形的蒙皮跟随，非刚性机械IK。",
    VEHICLE_FXN5C_0115_NAME = "复兴5C · 国铁蓝 FXN5C 0115 · 上局徐段",
    VEHICLE_FXN5C_0115_DESC = "FXN5C 0115，国铁蓝涂装；车身配属标识“上局徐段”。Co-Co轴式内燃机车，3530千瓦，120公里/小时。配属按用户要求定制，非官方核验结论。部分尺寸和隐藏细节为照片估算；连接杆为会变形的蒙皮跟随，非刚性机械IK。",
    VEHICLE_FXN5C_7006_NAME = "复兴5C · 金温铁路 FXN5C 7006 · 金温 温段",
    VEHICLE_FXN5C_7006_DESC = "FXN5C 7006，金温铁路涂装；车身配属标识“金温 温段”。Co-Co轴式内燃机车，3530千瓦，120公里/小时。配属按用户要求定制，非官方核验结论。部分尺寸和隐藏细节为照片估算；连接杆为会变形的蒙皮跟随，非刚性机械IK。",
    VEHICLE_FXN5C_7005_NAME = "复兴5C · 金温铁路 FXN5C 7005 · 金温 温段",
    VEHICLE_FXN5C_7005_DESC = "FXN5C 7005，金温铁路涂装；车身配属标识“金温 温段”。Co-Co轴式内燃机车，3530千瓦，120公里/小时。配属按用户要求定制，非官方核验结论。部分尺寸和隐藏细节为照片估算；连接杆为会变形的蒙皮跟随，非刚性机械IK。",
    VEHICLE_FXN5C_NAME = "复兴5C · 国铁蓝 FXN5C 0051 · 上局沪段",
    VEHICLE_FXN5C_DESC = "FXN5C 0051，国铁蓝涂装；车身配属标识“上局沪段”。Co-Co轴式内燃机车，3530千瓦，120公里/小时。配属按用户要求定制，非官方核验结论。部分尺寸和隐藏细节为照片估算；连接杆为会变形的蒙皮跟随，非刚性机械IK。",
    VEHICLE_FXN5C_JINWEN_NAME = "复兴5C · 金温铁路 FXN5C 7006 · 金温 温段",
    VEHICLE_FXN5C_JINWEN_DESC = "FXN5C 7006，金温铁路涂装；车身配属标识“金温 温段”。Co-Co轴式内燃机车，3530千瓦，120公里/小时。配属按用户要求定制，非官方核验结论。部分尺寸和隐藏细节为照片估算；连接杆为会变形的蒙皮跟随，非刚性机械IK。",
  },
}
end
