function data()
return {
  en = {
    MOD_NAME = "FXN5C v0.24 — China Railway & Jinwen Railway / 10 Variants",
    MOD_DESC = "[h1]China Railway FXN5C Diesel Locomotive[/h1]\nChina Railway blue and Jinwen Railway liveries, ten numbered variants for Transport Fever 2.\n\n[h2]Contents[/h2]\nChina Railway: 0051, 0066 (Shanghai); 0096, 0102 (Nanjing East); 0057, 0081 (Hangzhou); 0035, 0115 (Xuzhou).\nJinwen Railway: 7005, 7006. Two purchase groups, I/II end markings, multiple LODs and directional lighting.\n\n[h2]In-game configuration[/h2]\nPower: 3530 kW. Tractive effort: 580 kN. Top speed: 120 km/h. Weight: 150 t.\nAvailable in all years by default; optionally keep model years (CR: 2024, Jinwen: 2025). Depot markings and dates are project configurations, not certified real-world histories.\n\n[h2]Version and limitations[/h2]\nv0.24 refines the roof profile, paint boundaries, equipment, front markings and Jinwen front stripes, with directional red/moon-white lamps. This is a reference-based reconstruction, not factory CAD. Linkage rods still use deforming skinning rather than exact rigid joints. Extreme curves and hidden structures need further refinement. Static resources have been checked; systematic in-game validation is still pending. Project renders are not game screenshots. Per-number leading inner-lamp colors are custom configurations, not claims about real wiring.\n\n[h2]Editable models and community refinement[/h2]\n[url=https://github.com/Manfredss/fxn5c-tpf2]Source files, issues and contribution guide[/url]\nEditable Blender scenes, static FBXs and generation/checking scripts are provided. The incremental build has historical baseline dependencies; read the build guide first.\n\n[h2]License[/h2]\nOriginal models, textures and asset data: CC BY-NC-SA 4.0 (attribution, noncommercial, share alike). You may modify and share noncommercial adaptations under that license without asking each time. Credit the project, link the license and describe your changes.\nOriginal program logic: MIT (commercial code use permitted, not commercial model use). Third-party railway marks, font designs and reference materials are excluded from these grants. See the repository license scope and notices.\n\n[h2]Credits and feedback[/h2]\nProject initiator/reviewer: Manfredss / [ihtw] DisguiseMyse1f. AI-assisted procedural modeling and scripting were used. Thanks to reference contributors; Dreamrail illustrations informed structural reconstruction. Original reference images are not distributed. This is not an official manufacturer, railway-operator or Dreamrail release.\nBack up saves and avoid enabling duplicate local/Workshop copies. Please report version, number, reproduction steps and screenshots. Improvements to bogies, linkages, paint and testing are welcome!\n",
    FXN5C_YEAR_POLICY_NAME = "Vehicle availability years",
    FXN5C_YEAR_POLICY_TOOLTIP = "Only these FXN5C variants and their two purchase-group headers are affected. Ignore years: available in every game year. Keep model years: CR from 2024, Jinwen from 2025. Existing purchased vehicles are not deleted.",
    FXN5C_YEAR_IGNORE = "Ignore years (default)",
    FXN5C_YEAR_KEEP = "Keep model years (2024 / 2025)",
    VEHICLE_FXN5C_MENU_CR_NAME = "FXN5C — China Railway Blue",
    VEHICLE_FXN5C_MENU_CR_DESC = "China Railway blue: eight numbered variants. Select a vehicle within this group. Depot assignments are customized at the user’s request.",
    VEHICLE_FXN5C_MENU_JINWEN_NAME = "FXN5C — Jinwen Railway",
    VEHICLE_FXN5C_MENU_JINWEN_DESC = "Jinwen Railway blue/white/red: 7006 and 7005. Select a vehicle within this group. Depot assignments are customized at the user’s request.",
    VEHICLE_FXN5C_0051_NAME = "FXN5C 0051 — China Railway Blue / Shanghai Bureau · Shanghai Depot",
    VEHICLE_FXN5C_0051_DESC = "FXN5C 0051, China Railway Blue; Shanghai Bureau · Shanghai Depot markings. Co-Co diesel locomotive, 3,530 kW, 120 km/h. This depot assignment is a user-requested customization, not an officially verified allocation. Dimensions and hidden details are photo-based approximations. The connecting rod uses deforming skinning, not rigid mechanical IK.",
    VEHICLE_FXN5C_0096_NAME = "FXN5C 0096 — China Railway Blue / Shanghai Bureau · Nanjing East Depot",
    VEHICLE_FXN5C_0096_DESC = "FXN5C 0096, China Railway Blue; Shanghai Bureau · Nanjing East Depot markings. Co-Co diesel locomotive, 3,530 kW, 120 km/h. This depot assignment is a user-requested customization, not an officially verified allocation. Dimensions and hidden details are photo-based approximations. The connecting rod uses deforming skinning, not rigid mechanical IK.",
    VEHICLE_FXN5C_0102_NAME = "FXN5C 0102 — China Railway Blue / Shanghai Bureau · Nanjing East Depot",
    VEHICLE_FXN5C_0102_DESC = "FXN5C 0102, China Railway Blue; Shanghai Bureau · Nanjing East Depot markings. Co-Co diesel locomotive, 3,530 kW, 120 km/h. This depot assignment is a user-requested customization, not an officially verified allocation. Dimensions and hidden details are photo-based approximations. The connecting rod uses deforming skinning, not rigid mechanical IK.",
    VEHICLE_FXN5C_0057_NAME = "FXN5C 0057 — China Railway Blue / Shanghai Bureau · Hangzhou Depot",
    VEHICLE_FXN5C_0057_DESC = "FXN5C 0057, China Railway Blue; Shanghai Bureau · Hangzhou Depot markings. Co-Co diesel locomotive, 3,530 kW, 120 km/h. This depot assignment is a user-requested customization, not an officially verified allocation. Dimensions and hidden details are photo-based approximations. The connecting rod uses deforming skinning, not rigid mechanical IK.",
    VEHICLE_FXN5C_0081_NAME = "FXN5C 0081 — China Railway Blue / Shanghai Bureau · Hangzhou Depot",
    VEHICLE_FXN5C_0081_DESC = "FXN5C 0081, China Railway Blue; Shanghai Bureau · Hangzhou Depot markings. Co-Co diesel locomotive, 3,530 kW, 120 km/h. This depot assignment is a user-requested customization, not an officially verified allocation. Dimensions and hidden details are photo-based approximations. The connecting rod uses deforming skinning, not rigid mechanical IK.",
    VEHICLE_FXN5C_0066_NAME = "FXN5C 0066 — China Railway Blue / Shanghai Bureau · Shanghai Depot",
    VEHICLE_FXN5C_0066_DESC = "FXN5C 0066, China Railway Blue; Shanghai Bureau · Shanghai Depot markings. Co-Co diesel locomotive, 3,530 kW, 120 km/h. This depot assignment is a user-requested customization, not an officially verified allocation. Dimensions and hidden details are photo-based approximations. The connecting rod uses deforming skinning, not rigid mechanical IK.",
    VEHICLE_FXN5C_0035_NAME = "FXN5C 0035 — China Railway Blue / Shanghai Bureau · Xuzhou Depot",
    VEHICLE_FXN5C_0035_DESC = "FXN5C 0035, China Railway Blue; Shanghai Bureau · Xuzhou Depot markings. Co-Co diesel locomotive, 3,530 kW, 120 km/h. This depot assignment is a user-requested customization, not an officially verified allocation. Dimensions and hidden details are photo-based approximations. The connecting rod uses deforming skinning, not rigid mechanical IK.",
    VEHICLE_FXN5C_0115_NAME = "FXN5C 0115 — China Railway Blue / Shanghai Bureau · Xuzhou Depot",
    VEHICLE_FXN5C_0115_DESC = "FXN5C 0115, China Railway Blue; Shanghai Bureau · Xuzhou Depot markings. Co-Co diesel locomotive, 3,530 kW, 120 km/h. This depot assignment is a user-requested customization, not an officially verified allocation. Dimensions and hidden details are photo-based approximations. The connecting rod uses deforming skinning, not rigid mechanical IK.",
    VEHICLE_FXN5C_7006_NAME = "FXN5C 7006 — Jinwen Railway / Jinwen Railway · Wenzhou Depot",
    VEHICLE_FXN5C_7006_DESC = "FXN5C 7006, Jinwen Railway; Jinwen Railway · Wenzhou Depot markings. Co-Co diesel locomotive, 3,530 kW, 120 km/h. This depot assignment is a user-requested customization, not an officially verified allocation. Dimensions and hidden details are photo-based approximations. The connecting rod uses deforming skinning, not rigid mechanical IK.",
    VEHICLE_FXN5C_7005_NAME = "FXN5C 7005 — Jinwen Railway / Jinwen Railway · Wenzhou Depot",
    VEHICLE_FXN5C_7005_DESC = "FXN5C 7005, Jinwen Railway; Jinwen Railway · Wenzhou Depot markings. Co-Co diesel locomotive, 3,530 kW, 120 km/h. This depot assignment is a user-requested customization, not an officially verified allocation. Dimensions and hidden details are photo-based approximations. The connecting rod uses deforming skinning, not rigid mechanical IK.",
    VEHICLE_FXN5C_NAME = "FXN5C 0051 — China Railway Blue / Shanghai Bureau · Shanghai Depot",
    VEHICLE_FXN5C_DESC = "FXN5C 0051, China Railway Blue; Shanghai Bureau · Shanghai Depot markings. Co-Co diesel locomotive, 3,530 kW, 120 km/h. This depot assignment is a user-requested customization, not an officially verified allocation. Dimensions and hidden details are photo-based approximations. The connecting rod uses deforming skinning, not rigid mechanical IK.",
    VEHICLE_FXN5C_JINWEN_NAME = "FXN5C 7006 — Jinwen Railway / Jinwen Railway · Wenzhou Depot",
    VEHICLE_FXN5C_JINWEN_DESC = "FXN5C 7006, Jinwen Railway; Jinwen Railway · Wenzhou Depot markings. Co-Co diesel locomotive, 3,530 kW, 120 km/h. This depot assignment is a user-requested customization, not an officially verified allocation. Dimensions and hidden details are photo-based approximations. The connecting rod uses deforming skinning, not rigid mechanical IK.",
  },
  zh_CN = {
    MOD_NAME = "复兴5C（FXN5C）v0.24 国铁／金温铁路 · 10车号",
    MOD_DESC = "[h1]复兴5C（FXN5C）内燃机车[/h1]\n国铁蓝与金温铁路，两套涂装、十个车号，为《狂热运输2》制作。\n\n从一台能开进游戏的机车，到一台经得起细看的模型，还有不少路要走。本项目开放可编辑源文件，欢迎喜欢 FXN5C 的朋友继续精细化：一个轴箱、一段管路、一处涂装边界，都是有价值的改进。\n\n[h2]MOD 内容[/h2]\n[list]\n[*]国铁蓝：上局沪段 0051、0066；上局宁东段 0096、0102；上局杭段 0057、0081；上局徐段 0035、0115。\n[*]金温铁路：7005、7006。\n[*]两个购买分组，I／II 端标识，多级 LOD 及方向灯光配置。\n[/list]\n\n[h2]游戏参数[/h2]\n[list]\n[*]功率：3530 kW\n[*]牵引力：580 kN\n[*]最高速度：120 km/h\n[*]重量：150 t\n[*]出现年份：默认不限年份；可在模组参数中选择国铁 2024 年起、金温 2025 年起。\n[/list]\n以上为模组配置；配属与年份不作为实车履历证明。\n\n[h2]本版更新与不足[/h2]\nv0.24 调整车顶截面与分色、设备位置和正面标识，修正金温正面蓝带留白、红带贯通，并配置按方向切换的灯光。\n模型根据照片和绘画参考重建，不是厂家 CAD。连接杆仍为蒙皮近似，可能弯曲／伸缩，极端曲线和隐藏结构仍待完善。已经过静态资源检查，尚缺系统游戏实测记录；项目渲染图不是游戏截图。前端内侧红／白灯按车号固定分配，不表示实车接线。\n\n[h2]安装与反馈[/h2]\n请先备份存档，不要同时启用同一模组的本地版和工坊版。遇到问题请提供版本、车号、复现步骤和截图，可在留言区或 GitHub Issues 反馈。\n\n[h2]模型源文件与授权[/h2]\n[url=https://github.com/Manfredss/fxn5c-tpf2]GitHub：Manfredss/fxn5c-tpf2[/url]\n提供可编辑 Blender 场景、静态 FBX、生成／检查脚本与贡献指南。历史增量构建有基线依赖，请先阅读构建说明。\n\n[b]原创模型与贴图：CC BY-NC-SA 4.0（署名—非商业性使用—相同方式共享）。[/b]\n允许在许可范围内修改、重涂及公开分享非商用改进版，无需逐次申请；请保留署名、许可链接并说明修改，不得未经另行授权用于商业目的。\n原创脚本逻辑采用 MIT，允许脚本商用，但不授予模型商用权。第三方铁路标志、字形及资料不包含在本项目的授权范围内，完整边界见仓库许可与第三方说明。\n\n[h2]制作与致谢[/h2]\n项目发起与外观审核：Manfredss / [ihtw] DisguiseMyse1f。制作使用 AI 辅助建模与脚本开发。\n感谢提供实车照片与资料的朋友；结构参考包括 Dreamrail 绘画，铁路徽标来源另见仓库。参考原图不随模组分发；参考作者不等同于本项目合作作者或授权方。\n本项目非厂家、铁路运营方或 Dreamrail 官方作品。欢迎一起把它做得更好。\n",
    FXN5C_YEAR_POLICY_NAME = "车辆可用年份",
    FXN5C_YEAR_POLICY_TOOLTIP = "仅影响本模组10个车号及2个购买分组。忽略年份：任意游戏年份可购；保留模型年份：国铁2024年起、金温2025年起。不会删除已经购买的车辆。",
    FXN5C_YEAR_IGNORE = "忽略年份（默认）",
    FXN5C_YEAR_KEEP = "保留模型年份（2024／2025）",
    VEHICLE_FXN5C_MENU_CR_NAME = "复兴5C · 国铁蓝",
    VEHICLE_FXN5C_MENU_CR_DESC = "国铁蓝涂装，共8个车号。请在分组中选择具体车辆；配属标识按用户要求定制。",
    VEHICLE_FXN5C_MENU_JINWEN_NAME = "复兴5C · 金温铁路",
    VEHICLE_FXN5C_MENU_JINWEN_DESC = "金温铁路蓝白红涂装，包含7006、7005。请在分组中选择具体车辆；配属标识按用户要求定制。",
    VEHICLE_FXN5C_0051_NAME = "复兴5C · 国铁蓝 FXN5C 0051 · 上局沪段",
    VEHICLE_FXN5C_0051_DESC = "FXN5C 0051，国铁蓝涂装；车身配属标识“上局沪段”。Co-Co轴式内燃机车，3530千瓦，120公里/小时。配属按用户要求定制，非官方核验结论。部分尺寸和隐藏细节为照片估算；连接杆为会变形的蒙皮跟随，非刚性机械IK。",
    VEHICLE_FXN5C_0096_NAME = "复兴5C · 国铁蓝 FXN5C 0096 · 上局宁东段",
    VEHICLE_FXN5C_0096_DESC = "FXN5C 0096，国铁蓝涂装；车身配属标识“上局宁东段”。Co-Co轴式内燃机车，3530千瓦，120公里/小时。配属按用户要求定制，非官方核验结论。部分尺寸和隐藏细节为照片估算；连接杆为会变形的蒙皮跟随，非刚性机械IK。",
    VEHICLE_FXN5C_0102_NAME = "复兴5C · 国铁蓝 FXN5C 0102 · 上局宁东段",
    VEHICLE_FXN5C_0102_DESC = "FXN5C 0102，国铁蓝涂装；车身配属标识“上局宁东段”。Co-Co轴式内燃机车，3530千瓦，120公里/小时。配属按用户要求定制，非官方核验结论。部分尺寸和隐藏细节为照片估算；连接杆为会变形的蒙皮跟随，非刚性机械IK。",
    VEHICLE_FXN5C_0057_NAME = "复兴5C · 国铁蓝 FXN5C 0057 · 上局杭段",
    VEHICLE_FXN5C_0057_DESC = "FXN5C 0057，国铁蓝涂装；车身配属标识“上局杭段”。Co-Co轴式内燃机车，3530千瓦，120公里/小时。配属按用户要求定制，非官方核验结论。部分尺寸和隐藏细节为照片估算；连接杆为会变形的蒙皮跟随，非刚性机械IK。",
    VEHICLE_FXN5C_0081_NAME = "复兴5C · 国铁蓝 FXN5C 0081 · 上局杭段",
    VEHICLE_FXN5C_0081_DESC = "FXN5C 0081，国铁蓝涂装；车身配属标识“上局杭段”。Co-Co轴式内燃机车，3530千瓦，120公里/小时。配属按用户要求定制，非官方核验结论。部分尺寸和隐藏细节为照片估算；连接杆为会变形的蒙皮跟随，非刚性机械IK。",
    VEHICLE_FXN5C_0066_NAME = "复兴5C · 国铁蓝 FXN5C 0066 · 上局沪段",
    VEHICLE_FXN5C_0066_DESC = "FXN5C 0066，国铁蓝涂装；车身配属标识“上局沪段”。Co-Co轴式内燃机车，3530千瓦，120公里/小时。配属按用户要求定制，非官方核验结论。部分尺寸和隐藏细节为照片估算；连接杆为会变形的蒙皮跟随，非刚性机械IK。",
    VEHICLE_FXN5C_0035_NAME = "复兴5C · 国铁蓝 FXN5C 0035 · 上局徐段",
    VEHICLE_FXN5C_0035_DESC = "FXN5C 0035，国铁蓝涂装；车身配属标识“上局徐段”。Co-Co轴式内燃机车，3530千瓦，120公里/小时。配属按用户要求定制，非官方核验结论。部分尺寸和隐藏细节为照片估算；连接杆为会变形的蒙皮跟随，非刚性机械IK。",
    VEHICLE_FXN5C_0115_NAME = "复兴5C · 国铁蓝 FXN5C 0115 · 上局徐段",
    VEHICLE_FXN5C_0115_DESC = "FXN5C 0115，国铁蓝涂装；车身配属标识“上局徐段”。Co-Co轴式内燃机车，3530千瓦，120公里/小时。配属按用户要求定制，非官方核验结论。部分尺寸和隐藏细节为照片估算；连接杆为会变形的蒙皮跟随，非刚性机械IK。",
    VEHICLE_FXN5C_7006_NAME = "复兴5C · 金温铁路 FXN5C 7006 · 金温 温段",
    VEHICLE_FXN5C_7006_DESC = "FXN5C 7006，金温铁路涂装；车身配属标识“金温 温段”。Co-Co轴式内燃机车，3530千瓦，120公里/小时。配属按用户要求定制，非官方核验结论。部分尺寸和隐藏细节为照片估算；连接杆为会变形的蒙皮跟随，非刚性机械IK。",
    VEHICLE_FXN5C_7005_NAME = "复兴5C · 金温铁路 FXN5C 7005 · 金温 温段",
    VEHICLE_FXN5C_7005_DESC = "FXN5C 7005，金温铁路涂装；车身配属标识“金温 温段”。Co-Co轴式内燃机车，3530千瓦，120公里/小时。配属按用户要求定制，非官方核验结论。部分尺寸和隐藏细节为照片估算；连接杆为会变形的蒙皮跟随，非刚性机械IK。",
    VEHICLE_FXN5C_NAME = "复兴5C · 国铁蓝 FXN5C 0051 · 上局沪段",
    VEHICLE_FXN5C_DESC = "FXN5C 0051，国铁蓝涂装；车身配属标识“上局沪段”。Co-Co轴式内燃机车，3530千瓦，120公里/小时。配属按用户要求定制，非官方核验结论。部分尺寸和隐藏细节为照片估算；连接杆为会变形的蒙皮跟随，非刚性机械IK。",
    VEHICLE_FXN5C_JINWEN_NAME = "复兴5C · 金温铁路 FXN5C 7006 · 金温 温段",
    VEHICLE_FXN5C_JINWEN_DESC = "FXN5C 7006，金温铁路涂装；车身配属标识“金温 温段”。Co-Co轴式内燃机车，3530千瓦，120公里/小时。配属按用户要求定制，非官方核验结论。部分尺寸和隐藏细节为照片估算；连接杆为会变形的蒙皮跟随，非刚性机械IK。",
  },
}
end
