"""Coaxial axle-bearing correction, without moving a wheel or native node.

Only polygons exactly generated by the retained axlebox/pocket/sleeve recipes
are replaced. Triangle matching also supports native-readback LOD1 meshes.
The old arbitrary 120 mm cover offset is removed; the complete carrier is
reseated and its damper is shortened between the moved lower and fixed upper
clevis. Dimensions beyond the established running axes remain reference-fit.
"""
from collections import Counter
import json
import math
from pathlib import Path

import bpy
from bogie_details_v20 import Batch, AXLES, AXLE_HEIGHT, _axlebox

SHIFT = AXLE_HEIGHT - .505


class PartBatch(Batch):
    def __init__(self,builder):
        super().__init__(builder)
        self.parts=[]

    def add(self,name,verts,faces,mat='graphite',smooth=False):
        first=len(self.v); start=len(self.f)
        super().add(name,verts,faces,mat,smooth)
        self.parts.append({'role':name,'vertex_start':first,'vertex_count':len(verts),
                           'polygon_start':start,'polygon_count':len(faces)})


def key(points):
    # Native streams are float32. Six decimals is much smaller than the
    # smallest bolt, but tolerates the Blender/native float round trip.
    return tuple(sorted(tuple(round(float(v),6) for v in p) for p in points))


def _pockets(m):
    for side in (-1,1):
        for x in AXLES:
            bottom=.789 if abs(x)<.01 else .840
            for dx in (-.413,.413):
                sx=x+dx
                m.profile('spring_upper_pocket',[(sx-.15,bottom),(sx+.15,bottom),
                    (sx+.15,bottom+.045),(sx+.10,1.110),(sx-.10,1.110),
                    (sx-.15,bottom+.045)],side*1.14,.28,'graphite')


def _damper_map(z):
    # Low eye .587 -> .707, high eye remains 1.060. Keep real upper-frame
    # roots unchanged by limiting the transformation above the eye centre.
    if z>=1.060:return z
    if z<=.587:return z+SHIFT
    return .707+(z-.587)*((1.060-.707)/(1.060-.587))


def recipe(builder,corrected=False,sleeves=False):
    m=PartBatch(builder)
    if sleeves:
        from bogie_details_v22 import _red_damper_sleeves
        for side in (-1,1):_red_damper_sleeves(m,side)
        if corrected:
            m.v=[(x,y,_damper_map(z)) for x,y,z in m.v]
        return m
    for side in (-1,1):
        for x in AXLES:_axlebox(m,x,side)
    _pockets(m)
    if not corrected:return m
    for part in m.parts:
        role=part['role'];start=part['vertex_start'];stop=start+part['vertex_count']
        for i in range(start,stop):
            x,y,z=m.v[i]
            if role.startswith('damper_'):
                z=_damper_map(z)
            elif role=='spring_upper_pocket':
                if z<1.109:z+=SHIFT
            elif role in ('centre_open_saddle','centre_saddle_ear'):
                z+=AXLE_HEIGHT-.572
            elif role in ('centre_station_saddle','centre_short_guide'):
                # The fixed saddle roof/short guides already connect to the
                # middle frame; only its visible lower shell was miscentred.
                pass
            elif role=='axlebox_housing':
                z+=AXLE_HEIGHT-.507
            elif role=='axle_sensor_lead':
                # Rebuilt below with an actual cover contact and main return.
                pass
            else:
                z+=SHIFT
            if role=='guide_wear_plate':
                y-=math.copysign(.009,y)
            elif role=='outer_station_fork_cheek':
                y-=math.copysign(.020,y)
            elif role=='bearing_cover_bolt':
                y-=math.copysign(.005,y)
            m.v[i]=(x,y,z)
    # Replace old detached sensor lead with one whose first/last rings enter
    # the bearing cover and the retained bogie main respectively.
    keep=[i for p in m.parts if p['role']!='axle_sensor_lead'
          for i in range(p['polygon_start'],p['polygon_start']+p['polygon_count'])]
    old=m; m=PartBatch(builder)
    for p in old.parts:
        if p['role']=='axle_sensor_lead':continue
        indices=range(p['vertex_start'],p['vertex_start']+p['vertex_count'])
        first=p['vertex_start'];ps=p['polygon_start'];pe=ps+p['polygon_count']
        faces=[tuple(v-first for v in f) for f in old.f[ps:pe]]
        m.add(p['role'],[old.v[i] for i in indices],faces,
              old.materials[old.mi[ps]],old.smooth[ps:pe])
    for side in (-1,1):
        for x in AXLES:
            # The wheel axle ends at |Y| 1.080. This sleeve overlaps that
            # axle and the visible housing, providing the missing inner seat.
            m.cyl('coaxial_inner_bearing',(x,side*1.087,AXLE_HEIGHT),.102,.246,
                  'cast_steel',segments=16 if builder.lod==0 else 10)
            if abs(x)>.01:
                for d in (-1,1):
                    m.box('fork_to_frame_root',(x+d*.297,side*1.270,1.120),
                          (.092,.130,.066),'cast_steel',.008)
            if abs(x)>.01 and builder.lod==0:
                # Take off farther inboard along the SAME retained air main.
                # A tip at x+.24,z1.195 entered the fixed sill at 10 degrees;
                # bending only the intervening cable could not fix that tip.
                # These Z values interpolate the actual v20 mainline path.
                main_x=math.copysign(1.10,x)
                main_z=1.168+(.027*(1.10-.70)/.75 if x>0 else 0)
                m.tube('axle_sensor_lead',[(x+.045,side*1.353,.675),
                    (x+.115,side*1.405,.737),(x+.130,side*1.402,.865),
                    (x+.170,side*1.345,1.052),(main_x,side*1.301,main_z)],
                    .009,'black',6)
    return m


def auxiliary_recipe(builder,end,corrected=False):
    from bogie_details_v22 import _auxiliary,_fit_under_sill
    m=PartBatch(builder)
    for side in (-1,1):
        start=len(m.v);_auxiliary(m,end,side);_fit_under_sill(m,start,side)
    if corrected:
        # The old face plate was separated from the housing by 0.5 mm, and
        # its decorative screws had another 0.5--5 mm of air beneath them.
        # Seat the complete lid assembly; no external silhouette or root is
        # moved longitudinally and the upper frame mounting is unchanged.
        offsets={'auxiliary_lid_field':.003,'auxiliary_lid_border':.003,
                 'auxiliary_horizontal_rib':.003,'auxiliary_top_latch':.003,
                 'junction_lid_screw':.002,'auxiliary_lid_screw':.009}
        for p in m.parts:
            offset=offsets.get(p['role'],0)
            if not offset:continue
            for i in range(p['vertex_start'],p['vertex_start']+p['vertex_count']):
                x,y,z=m.v[i];m.v[i]=(x,y-math.copysign(offset,y),z)
    return m


def _triangles(obj):
    obj.data.calc_loop_triangles()
    return Counter(key([obj.data.vertices[i].co for i in t.vertices])
                   for t in obj.data.loop_triangles)


def _replace(obj,builder,old_batch,new_batch,jinwen,label):
    old=obj.data
    temporary=old_batch.finish('_gear23_legacy_recipe',None)
    targets=_triangles(temporary)
    old.calc_loop_triangles()
    by_polygon={}
    for t in old.loop_triangles:
        by_polygon.setdefault(t.polygon_index,[]).append(key([old.vertices[i].co for i in t.vertices]))
    kept=[]; removed=[]
    for face in old.polygons:
        local=Counter(by_polygon[face.index])
        if all(targets[k]>=count for k,count in local.items()):
            removed.append(face.index);targets.subtract(local)
        else:kept.append(face)
    missing=sum(targets.values())
    bpy.data.objects.remove(temporary,do_unlink=True)
    if missing:raise RuntimeError(f'{obj.name} {label}: {missing} exact recipe triangles missing; no spatial deletion allowed')
    new_obj=new_batch.finish('_gear23_new_recipe',None);new=new_obj.data
    retained=sorted({i for p in kept for i in p.vertices}); lookup={i:j for j,i in enumerate(retained)}
    vertices=[tuple(old.vertices[i].co) for i in retained]+[tuple(v.co) for v in new.vertices]
    faces=[tuple(lookup[i] for i in p.vertices) for p in kept]
    faces.extend(tuple(len(retained)+i for i in p.vertices) for p in new.polygons)
    mesh=bpy.data.meshes.new(obj.name+'_gear23_'+label)
    mesh.from_pydata(vertices,[],faces);mesh.update()
    mats=list(old.materials);mapping={'graphite':'jw_frame','spring_steel':'jw_frame','cast_steel':'jw_spring'} if jinwen else {}
    new_mats=[]
    for mat in new.materials:
        short=Path(mat.name).name;actual=builder.mat(mapping.get(short,short))
        if actual not in mats:mats.append(actual)
        new_mats.append(mats.index(actual))
    for mat in mats:mesh.materials.append(mat)
    material_smooth=[(p.material_index,p.use_smooth) for p in kept]+[(new_mats[p.material_index],p.use_smooth) for p in new.polygons]
    for p,(mi,smooth) in zip(mesh.polygons,material_smooth):p.material_index=mi;p.use_smooth=smooth
    old_loops=[i for p in kept for i in p.loop_indices]
    for layer in old.uv_layers:
        target=mesh.uv_layers.new(name=layer.name)
        for i,j in enumerate(old_loops):target.data[i].uv=layer.data[j].uv
        for loop in list(mesh.loops)[len(old_loops):]:
            co=mesh.vertices[loop.vertex_index].co;target.data[loop.index].uv=(co.x*.071+.5,co.z*.14+co.y*.03)
    mesh.normals_split_custom_set([tuple(old.corner_normals[i].vector) for i in old_loops]+
                                  [tuple(n.vector) for n in new.corner_normals])
    # Prove all retained geometric surfaces, material assignments, UVs and
    # loop normals survived, rather than reporting only a face count.
    for a,b in zip(kept,mesh.polygons):
        assert a.material_index==b.material_index
        for va,vb in zip(a.vertices,b.vertices):assert old.vertices[va].co==mesh.vertices[vb].co
        for la,lb in zip(a.loop_indices,b.loop_indices):
            for layer in old.uv_layers:assert layer.data[la].uv==mesh.uv_layers[layer.name].data[lb].uv
    obj.data=mesh
    ranges=[dict(p,polygon_start=p['polygon_start']+len(kept),vertex_start=p['vertex_start']+len(retained)) for p in new_batch.parts]
    face_index={face.index:i for i,face in enumerate(kept)}
    for prop in list(obj.keys()):
        if prop.startswith('gear23_') and prop.endswith('_roles'):
            updated=[]
            for row in json.loads(obj[prop]):
                indices=[face_index[i] for i in range(row['polygon_start'],row['polygon_start']+row['polygon_count']) if i in face_index]
                if indices:
                    assert indices==list(range(indices[0],indices[0]+len(indices)))
                    updated.append(dict(row,polygon_start=indices[0],polygon_count=len(indices)))
            obj[prop]=json.dumps(updated)
    obj['gear23_'+label+'_roles']=json.dumps(ranges)
    obj['gear23_'+label+'_applied']=True
    if label in ('sleeve','auxiliary') and obj.get('bogie22_roles_json'):
        revised=[]
        for row in json.loads(obj['bogie22_roles_json']):
            indices=[face_index[i] for i in range(row['first_polygon'],row['first_polygon']+row['polygon_count']) if i in face_index]
            if indices:
                assert indices==list(range(indices[0],indices[0]+len(indices)))
                revised.append(dict(row,first_polygon=indices[0],polygon_count=len(indices)))
        revised.extend({'role':r['role'],'first_polygon':r['polygon_start'],'polygon_count':r['polygon_count']} for r in ranges)
        obj['bogie22_roles_json']=json.dumps(revised)
    mesh.calc_loop_triangles()
    result={'object':obj.name,'pass':label,'removed_polygons':len(removed),
            'removed_triangles':sum(len(by_polygon[i]) for i in removed),
            'retained_polygons':len(kept),'replacement_polygons':len(new.polygons),
            'retained_position_material_uv_exact':True,'new_triangles':len(mesh.loop_triangles)}
    bpy.data.objects.remove(new_obj,do_unlink=True)
    return result


def apply(builder,jinwen=False):
    """Patch named b1/b2 meshes from saved source or native readback.

    Native readback frames contain the v22 sleeves inline. Source stores them
    in bogie22_details_b*. Neither route adds/reorders native hierarchy nodes.
    LOD2 is unchanged (bearings not separately visible at that distance).
    Returns geometry-derived change reports; no scene saving/export here.
    """
    if builder.lod>=2:return []
    out=[]
    for index in (1,2):
        obj=bpy.data.objects.get(f'b{index}')
        if obj is None:raise RuntimeError(f'Missing actual bogie b{index}')
        if not obj.get('gear23_axle_applied'):
            out.append(_replace(obj,builder,recipe(builder),recipe(builder,True),jinwen,'axle'))
        sleeve_obj=bpy.data.objects.get(f'bogie22_details_b{index}') or obj
        if not sleeve_obj.get('gear23_sleeve_applied'):
            out.append(_replace(sleeve_obj,builder,recipe(builder,sleeves=True),
                                recipe(builder,True,True),jinwen,'sleeve'))
        if not sleeve_obj.get('gear23_auxiliary_applied'):
            end=1 if index==1 else -1
            out.append(_replace(sleeve_obj,builder,auxiliary_recipe(builder,end),
                                auxiliary_recipe(builder,end,True),jinwen,'auxiliary'))
    bpy.context.view_layer.update()
    return out
